apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nginx.treenetsolution.com
spec:
  selector:
    run: nginx
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
