apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mywebsite-cert
  namespace: default
spec:
  secretName: mywebsite-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - treenetsolution.com
